# Generated by Django 2.1.3 on 2018-11-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_remove_student_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pic',
        ),
    ]
