# Generated by Django 2.1.3 on 2018-12-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20181203_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
        migrations.AddField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image'),
        ),
    ]
