# Generated by Django 2.1.3 on 2018-12-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20181203_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='amanyadav2202@gmail.com', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='book_image'),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
