# Generated by Django 2.1.3 on 2018-12-04 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.CharField(choices=[('0', '0'), ('.5', '.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2.5', '2.5'), ('3', '3'), ('3.5', '3.5'), ('4', '4'), ('4.5', '4.5'), ('5', '5')], default='2', max_length=3),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='review',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
